### ISSUE TITLE
save a recording in portrait mode has a rotation problem

### ISSUE THREAD

**Issue by scheriff** [sourab-sharma/TouchToRecord#11]
I am trying to record a video in portrait mode with the front camera. I have removed screenOrientation="landscape" from FFmpegRecorderActivity in manifest.xml and removed margins from camera layout. 

Preview and recording is working but the resulting file is falsely rotated. Front camera footage is rotated 90 degrees clockwise, back camera footage is rotated 90 degrees counterclockwise. I couldn't find the reason for this. Any suggestions?

**Comment by sourab-sharma** [comment]
Please see updated code.
