### ISSUE TITLE
Missing imports

### ISSUE THREAD

**Issue by Simonida** [sourab-sharma/TouchToRecord#19]
Hi,

Thank you very much, this is a great project.
But I have noticed that some imports are missing:

import com.sourab.videorecorder.interfaces.Interfaces;
import com.sourab.videorecorder.util.CustomUtil;

Can you tell mi if there is some special configuration that needs to be set?

**Comment by sourab-sharma** [comment]
Hi,

Those 2 files were included to add watermark on video.
Somehow those 2 files didn't get pushed.
I will push soon.
Meanwhile you can remove the block : 
 if (CONSTANTS.DO_YOU_WANT_WATER_MARK_ON_VIDEO) {

}

**Comment by sourab-sharma** [comment]
Files added.
